# Generated by Django 5.1.7 on 2025-03-18 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=128,
                        verbose_name="Hashed Topic ID",
                    ),
                ),
                ("prompt", models.TextField(verbose_name="Prompt")),
                (
                    "subject",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="Subject"
                    ),
                ),
                ("response", models.TextField(verbose_name="Response")),
                ("prompt_vector", models.BinaryField(verbose_name="Prompt Vector")),
                ("response_vector", models.BinaryField(verbose_name="Response Vector")),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created Date"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified Date"
                    ),
                ),
            ],
            options={
                "verbose_name": "AgentMemory",
                "verbose_name_plural": "Knowledge Graph",
                "db_table": "octagent_memory",
            },
        ),
    ]
