# Generated by Django 5.1.7 on 2025-03-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentmemory",
            options={
                "verbose_name": "AgentMemory",
                "verbose_name_plural": "Knowledge Graphs",
            },
        ),
        migrations.AlterField(
            model_name="agentmemory",
            name="prompt_id",
            field=models.CharField(
                db_index=True,
                editable=False,
                max_length=64,
                verbose_name="Hashed Topic ID",
            ),
        ),
    ]
